#!/bin/bash 
version=0.1.0
show_usage(){
    echo "appspider version:${version}"
    echo ""
    echo "Usage:"
    echo "  spider <command> [options] [args]"
    echo ""
    echo "Available commands:"
    echo "  help     show this help infomation"
    echo "  auto     auto run"
    echo "  marketcontent    run index crawlers to get index infomation"
    echo "  marketupdate     update app"
    echo "  marketcomment  run commemt crawlers to crawl comments"
    echo "  app      run app crawlers to download apk"
    #echo "  img      download images"
    echo "  update   update download numbers and find new app"
    echo "  test <spider>   test spider"
    echo "  version  show version of umspider"
    echo ""
    echo "Use \"spider <command> -h\" to see more info about a command"
}

RunSpider(){
    for spider in `scrapy list |grep ${1}`;do
    {
       echo "scrapy crawl ${spider} "
    }
    done
}

StopSpiders()
{
     ps -aux |grep scrapy |grep -v grep |awk '{print $2}'|xargs kill -2
}

if test "$1" = "help" || test "$1" = "" ; then
    show_usage
elif test "$1" = "index" ; then
    echo "index crawlers start running ..."
    #RunSpider marketindex

elif test "$1" = "update" ; then 
    echo "update crawlers start running ..."
    #RunSpider marketupdate

elif test "$1" = "comment" ; then 
    echo "detail crawlers start running ..."
    #RunSpider marketcomment

elif test "$1" = "content" ; then 
    echo "detail crawlers start running ..."
    RunSpider marketcontent

elif test "$1" = "stop" ; then 
    echo "stopping spiders now ..."
    StopSpiders

elif test "$1" = "version" ; then 
    echo "spider:${version}"

elif test "$1" = "test" ; then 
    scrapy crawl $2 

elif test "$1" = "auto" ; then
    date >> log/umplus
    timestamp=`date  +%Y%m%d`
    scrapy crawl marketcontent -L DEBUG --logfile=log/${timestamp} &
    wait
    date >> log/umplus
else
    show_usage
fi
